const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY='debunker-passport-v1';
const form=$('#passportForm');
const {rules,evaluate:evaluateRisk}=DebunkerRisk;

function initialCase(){return{meta:{caseId:`DP-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`,caseTitle:'Nieuwe retourpartij',analyst:'',asOfDate:new Date().toISOString().slice(0,10)},fields:{},lineage:[],sources:[],audit:[]}}
let state=initialCase();

function readState(){
 state.meta={caseId:$('#caseId').value,caseTitle:$('#caseTitle').value,analyst:$('#analyst').value,asOfDate:$('#asOfDate').value};
 state.fields=Object.fromEntries(new FormData(form).entries());
 state.lineage=readRows('#lineageRows'); state.sources=readRows('#sourceRows');
}
function readRows(sel){return $$('.repeat-row',$(sel)).map(row=>Object.fromEntries($$('[data-key]',row).map(x=>[x.dataset.key,x.value])))}
function save(){const before=JSON.stringify({meta:state.meta,fields:state.fields,lineage:state.lineage,sources:state.sources});const oldFields={...(state.fields||{})};readState();const after=JSON.stringify({meta:state.meta,fields:state.fields,lineage:state.lineage,sources:state.sources});if(before!==after){const changed=[...new Set([...Object.keys(oldFields),...Object.keys(state.fields)].filter(k=>oldFields[k]!==state.fields[k]))];state.audit=state.audit||[];state.audit.push({at:new Date().toISOString(),changed:changed.length?changed:['meta/of rijen']});state.audit=state.audit.slice(-100)}localStorage.setItem(KEY,JSON.stringify(state));$('#saveState').textContent='Lokaal opgeslagen';analyse()}
let saveTimer;function queueSave(){ $('#saveState').textContent='Wijzigingen…';clearTimeout(saveTimer);saveTimer=setTimeout(save,250)}

function load(){
 try{state=JSON.parse(localStorage.getItem(KEY))||initialCase()}catch{state=initialCase()} state.audit=state.audit||[];
 $('#caseId').value=state.meta.caseId||'';$('#caseTitle').value=state.meta.caseTitle||'';$('#analyst').value=state.meta.analyst||'';$('#asOfDate').value=state.meta.asOfDate||'';
 Object.entries(state.fields||{}).forEach(([k,v])=>{const el=form.elements[k];if(el)el.value=v});
 (state.lineage||[]).forEach(v=>addRow('lineage',v));(state.sources||[]).forEach(v=>addRow('source',v));readState();analyse();
}

function addRow(type,values={}){const template=$(`#${type}Template`);const node=template.content.firstElementChild.cloneNode(true);Object.entries(values).forEach(([k,v])=>{const el=$(`[data-key="${k}"]`,node);if(el)el.value=v});$('.remove',node).addEventListener('click',()=>{node.remove();queueSave()});$$('input,select',node).forEach(x=>x.addEventListener('input',queueSave));$(`#${type}Rows`).append(node)}

function analyse(){
 const {active,score,coverage,label,note,color:colorName}=evaluateRisk(state.fields||{},state);const color=`var(--${colorName})`;
 $('#riskScore').textContent=score;$('#riskLabel').textContent=label;$('#riskNote').textContent=note;$('#riskRing').style.background=`conic-gradient(${color} ${score*3.6}deg,#d6d4ce 0deg)`;$('#coverageValue').textContent=`${coverage}%`;$('#coverageBar').style.width=`${coverage}%`;$('#signalCount').textContent=`${active.length} ${active.length===1?'signaal':'signalen'}`;
 const box=$('#signals');box.innerHTML='';if(!active.length)box.innerHTML='<p class="empty">Nog geen actieve inconsistenties. Dit is geen vrijgave of juridische conclusie.</p>';
 active.sort((a,b)=>b.points-a.points).forEach(r=>{const el=document.createElement('div');el.className=`signal ${r.severity}`;el.innerHTML=`<div><strong>${r.title}</strong><p>${r.text}</p></div>`;el.addEventListener('click',()=>document.getElementById(r.target).scrollIntoView({behavior:'smooth'}));box.append(el)});
 renderTimeline();renderAudit();
}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderTimeline(){const f=state.fields||{},events=[];if(f.deliveryDate)events.push({date:f.deliveryDate,title:'Oorspronkelijke levering',detail:f.bdnNumber||f.originalBatchId||'BDN/batch niet ingevuld'});if(f.firstComplaintDate)events.push({date:f.firstComplaintDate,title:'Eerste klacht',detail:f.incidentDescription||'Geen beschrijving'});if(f.transferDate)events.push({date:f.transferDate,title:'Geplande debunkering/transfer',detail:f.destination||'Bestemming niet ingevuld'});(state.lineage||[]).filter(x=>x.date).forEach(x=>events.push({date:x.date,title:x.action||'Partijhandeling',detail:`${x.childId||'Geen batch-ID'}${x.mass?` — ${x.mass} ton`:''}`}));events.sort((a,b)=>a.date.localeCompare(b.date));$('#timelineRows').innerHTML=events.length?events.map(e=>`<div class="timeline-event"><time>${e.date}</time><div><strong>${escapeHtml(e.title)}</strong><p>${escapeHtml(e.detail)}</p></div></div>`).join(''):'<p class="empty">Vul datums in om de tijdlijn op te bouwen.</p>'}
function renderAudit(){const audit=state.audit||[];$('#auditCount').textContent=`${audit.length} ${audit.length===1?'wijziging':'wijzigingen'}`;$('#auditRows').innerHTML=audit.length?audit.slice(-8).reverse().map(x=>`<p><time>${new Date(x.at).toLocaleString('nl-NL')}</time>${x.changed.map(escapeHtml).join(', ')}</p>`).join(''):'<p>Er zijn nog geen betekenisvolle wijzigingen opgeslagen.</p>'}

function report(){readState();const active=rules.filter(r=>r.when(state.fields,state));const rows=(obj)=>Object.entries(obj).map(([k,v])=>`- ${k}: ${v||'—'}`).join('\n');return `# Debunker Passport — ${state.meta.caseTitle}\n\n**Casus-ID:** ${state.meta.caseId}\n**Analist:** ${state.meta.analyst||'—'}\n**Peildatum:** ${state.meta.asOfDate||'—'}\n\n> Defensieve signalering; geen vaststelling van fraude of afvalstatus.\n\n## Signalen\n${active.length?active.map(r=>`- **${r.title}:** ${r.text}`).join('\n'):'- Geen actieve inconsistenties op basis van de ingevulde gegevens.'}\n\n## Gegevens\n${rows(state.fields)}\n\n## Partij-afstamming\n${state.lineage.length?state.lineage.map(x=>`- ${x.date||'—'} — ${x.childId||'—'} — ${x.action} — ${x.mass||'—'} ton`).join('\n'):'- Niet geregistreerd'}\n\n## Bronnen\n${state.sources.length?state.sources.map(x=>`- ${x.rating} — ${x.date||'—'} — ${x.reference||'—'}`).join('\n'):'- Niet geregistreerd'}\n`}
function download(){const blob=new Blob([report()],{type:'text/markdown;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${state.meta.caseId||'debunker-passport'}.md`;a.click();URL.revokeObjectURL(a.href)}
function downloadJson(){readState();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${state.meta.caseId||'debunker-passport'}.json`;a.click();URL.revokeObjectURL(a.href)}
async function sha256(text){if(globalThis.crypto?.subtle){const bytes=new TextEncoder().encode(text);const digest=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}return sha256Fallback(text)}
function sha256Fallback(ascii){function rightRotate(v,a){return(v>>>a)|(v<<(32-a))}const maxWord=Math.pow(2,32),words=[],asciiBitLength=ascii.length*8;let hash=sha256Fallback.h=sha256Fallback.h||[],k=sha256Fallback.k=sha256Fallback.k||[],primeCounter=k.length,isComposite={};for(let candidate=2;primeCounter<64;candidate++){if(!isComposite[candidate]){for(let i=0;i<313;i+=candidate)isComposite[i]=candidate;hash[primeCounter]=(Math.pow(candidate,.5)*maxWord)|0;k[primeCounter++]=(Math.pow(candidate,1/3)*maxWord)|0}}ascii+='\x80';while(ascii.length%64-56)ascii+='\x00';for(let i=0;i<ascii.length;i++){const j=ascii.charCodeAt(i);words[i>>2]|=j<<((3-i)%4)*8}words[words.length]=(asciiBitLength/maxWord)|0;words[words.length]=asciiBitLength;for(let j=0;j<words.length;){const w=words.slice(j,j+=16),oldHash=hash.slice(0);hash=hash.slice(0,8);for(let i=0;i<64;i++){const w15=w[i-15],w2=w[i-2],a=hash[0],e=hash[4];const temp1=hash[7]+(rightRotate(e,6)^rightRotate(e,11)^rightRotate(e,25))+((e&hash[5])^(~e&hash[6]))+k[i]+(w[i]=i<16?w[i]:(w[i-16]+(rightRotate(w15,7)^rightRotate(w15,18)^(w15>>>3))+w[i-7]+(rightRotate(w2,17)^rightRotate(w2,19)^(w2>>>10)))|0);const temp2=(rightRotate(a,2)^rightRotate(a,13)^rightRotate(a,22))+((a&hash[1])^(a&hash[2])^(hash[1]&hash[2]));hash=[(temp1+temp2)|0,a,hash[1],hash[2],(hash[3]+temp1)|0,hash[4],hash[5],hash[6]]}for(let i=0;i<8;i++)hash[i]=(hash[i]+oldHash[i])|0}let result='';for(let i=0;i<8;i++)for(let j=3;j+1;j--){const b=(hash[i]>>(j*8))&255;result+=(b<16?'0':'')+b.toString(16)}return result}
async function downloadIntegrity(){readState();const payload=JSON.stringify(state);const manifest={caseId:state.meta.caseId,generatedAt:new Date().toISOString(),algorithm:'SHA-256',sha256:await sha256(payload),bytes:new TextEncoder().encode(payload).length,note:'Hash van de compacte JSON-weergave van het dossier op het generatiemoment.'};const blob=new Blob([JSON.stringify(manifest,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${state.meta.caseId||'debunker-passport'}-integrity.json`;a.click();URL.revokeObjectURL(a.href)}
function validCase(data){return data&&data.meta&&typeof data.meta.caseId==='string'&&data.fields&&Array.isArray(data.lineage)&&Array.isArray(data.sources)}
function replaceCase(data){state=data;localStorage.setItem(KEY,JSON.stringify(state));location.reload()}
async function loadDemo(){if(!confirm('Historische geanonimiseerde demo laden? Exporteer eventueel eerst je huidige casus.'))return;const response=await fetch('demo-case.json');if(!response.ok)throw new Error('Demo kon niet worden geladen');replaceCase(await response.json())}
async function importJson(file){try{const data=JSON.parse(await file.text());if(!validCase(data))throw new Error('Onverwachte dossierstructuur');replaceCase(data)}catch(error){alert(`Import mislukt: ${error.message}`)}}
globalThis.DebunkerIntegrity={sha256};

$$('input,select,textarea',document).forEach(x=>x.addEventListener('input',queueSave));$('#addLineage').addEventListener('click',()=>addRow('lineage'));$('#addSource').addEventListener('click',()=>addRow('source'));$('#exportReport').addEventListener('click',download);$('#exportJson').addEventListener('click',downloadJson);$('#exportIntegrity').addEventListener('click',()=>downloadIntegrity().catch(e=>alert(e.message)));$('#loadDemo').addEventListener('click',()=>loadDemo().catch(e=>alert(e.message)));$('#importJson').addEventListener('change',e=>{if(e.target.files[0])importJson(e.target.files[0])});$('#newCase').addEventListener('click',()=>{if(confirm('Nieuwe casus starten? De huidige gegevens blijven alleen behouden als je eerst exporteert.')){localStorage.removeItem(KEY);location.reload()}});
$$('.nav-step').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.target;document.getElementById(id).scrollIntoView({behavior:'smooth'});$$('.nav-step').forEach(x=>x.classList.toggle('active',x===b))}));
load();
