'use strict';
const docs={
 'osint-dossier':{title:'OSINT-dossier: stookolie, afvalbijmenging en ketenfraude',file:'/onderzoek/OSINT-dossier-stookolie-en-afvalfraude.md'},
 '360-graden-werkboek':{title:'360°-OSINT-werkboek',file:'/onderzoek/360-graden-OSINT-werkboek.md'},
 'debunkering-ara-singapore':{title:'Debunkering Rotterdam/ARA–Singapore',file:'/onderzoek/debunkering-risicodossier-ARA-Singapore.md'},
 'internationale-casusmatrix':{title:'Vergelijkende internationale casusmatrix',file:'/onderzoek/vergelijkende-internationale-casusmatrix.md'},
 'historische-voorbeeldcasus':{title:'Ingevulde historische voorbeeldcasus',file:'/onderzoek/voorbeeldcasus-ECLI-NL-GHDHA-2018-3444.md'},
 'haven-regelgevingsmatrix':{title:'Internationale haven- en regelgevingsmatrix',file:'/onderzoek/internationale-haven-en-regelgevingsmatrix.md'},
 'stoffen-documenten-massabalans':{title:'Stoffen-, documenten- en massabalansmatrix',file:'/onderzoek/stoffen-documenten-en-massabalansmatrix.md'}
};
const routes={'OSINT-dossier-stookolie-en-afvalfraude.md':'osint-dossier','360-graden-OSINT-werkboek.md':'360-graden-werkboek','debunkering-risicodossier-ARA-Singapore.md':'debunkering-ara-singapore','vergelijkende-internationale-casusmatrix.md':'internationale-casusmatrix','voorbeeldcasus-ECLI-NL-GHDHA-2018-3444.md':'historische-voorbeeldcasus','internationale-haven-en-regelgevingsmatrix.md':'haven-regelgevingsmatrix','stoffen-documenten-en-massabalansmatrix.md':'stoffen-documenten-massabalans'};
const key=document.body.dataset.document,meta=docs[key],content=document.getElementById('readerContent'),toc=document.getElementById('readerToc');
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const slug=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function inline(s){let out=escapeHtml(s);out=out.replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>');out=out.replace(/\[([^\]]+)\]\(([^)]+)\)/g,(_,label,url)=>{const name=url.replace(/^\.\//,'');const internal=routes[name];const href=internal?`/documenten/${internal}`:url;const external=/^https?:/.test(href);return `<a href="${escapeHtml(href)}"${external?' target="_blank" rel="noopener"':''}>${label}</a>`});return out}
function markdown(md){const lines=md.replace(/\r/g,'').split('\n'),html=[];let i=0,inCode=false,code=[],list=null,quote=[];const closeList=()=>{if(list){html.push(`</${list}>`);list=null}};const closeQuote=()=>{if(quote.length){html.push(`<blockquote><p>${inline(quote.join(' '))}</p></blockquote>`);quote=[]}};while(i<lines.length){const line=lines[i];if(line.startsWith('```')){closeList();closeQuote();if(inCode){html.push(`<pre><code>${escapeHtml(code.join('\n'))}</code></pre>`);code=[];inCode=false}else inCode=true;i++;continue}if(inCode){code.push(line);i++;continue}if(/^\|.*\|\s*$/.test(line)&&i+1<lines.length&&/^\|?\s*:?-+/.test(lines[i+1])){closeList();closeQuote();const rows=[];rows.push(line);i+=2;while(i<lines.length&&/^\|.*\|\s*$/.test(lines[i]))rows.push(lines[i++]);const cells=r=>r.trim().replace(/^\||\|$/g,'').split('|').map(x=>x.trim());const head=cells(rows.shift());html.push('<div class="table-wrap"><table><thead><tr>'+head.map(x=>`<th>${inline(x)}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cells(r).map(x=>`<td>${inline(x)}</td>`).join('')+'</tr>').join('')+'</tbody></table></div>');continue}const heading=line.match(/^(#{1,4})\s+(.+)$/);if(heading){closeList();closeQuote();const level=heading[1].length,id=slug(heading[2]);html.push(`<h${level} id="${id}">${inline(heading[2])}</h${level}>`);i++;continue}if(/^>\s?/.test(line)){closeList();quote.push(line.replace(/^>\s?/,''));i++;continue}else closeQuote();const li=line.match(/^\s*([-*]|\d+\.)\s+(.+)$/);if(li){const kind=/\d/.test(li[1])?'ol':'ul';if(list!==kind){closeList();list=kind;html.push(`<${kind}>`)}html.push(`<li>${inline(li[2])}</li>`);i++;continue}else closeList();if(/^---+$/.test(line.trim()))html.push('<hr>');else if(line.trim())html.push(`<p>${inline(line.trim())}</p>`);i++}closeList();closeQuote();return html.join('\n')}
async function init(){if(!meta){content.innerHTML='<p class="reader-error">Onbekend document.</p>';return}document.title=meta.title+' — Debunker Passport';document.getElementById('readerTitle').textContent=meta.title;try{const response=await fetch(meta.file);if(!response.ok)throw new Error(`HTTP ${response.status}`);content.innerHTML=markdown(await response.text());const headings=[...content.querySelectorAll('h2,h3')];toc.innerHTML='<strong>Inhoud</strong>'+headings.map(h=>`<a href="#${h.id}">${h.textContent}</a>`).join('')}catch(error){content.innerHTML=`<p class="reader-error">Het document kon niet worden geladen (${escapeHtml(error.message)}).</p>`}}init();
