'use strict';
const nodes=[
{id:'batch',label:'Batch RT-041',type:'physical',kind:'Retourpartij',x:555,y:315,desc:'Fictieve partij die na een kwaliteitsklacht wordt teruggenomen.',facts:{Status:'Onbeslist',Massa:'842,6 t'},alerts:['Product- en afvalstatus zijn nog niet bevoegd gemotiveerd.']},
{id:'vessel',label:'M/V Example',type:'physical',kind:'Schip',x:150,y:145,desc:'Fictief afgevend schip, tank 3P.',facts:{IMO:'IMO 9000001',Tank:'3P'},alerts:[]},
{id:'barge',label:'Barge Delta',type:'physical',kind:'Ontvangend asset',x:155,y:490,desc:'Fictieve barge die de retourpartij ontvangt.',facts:{Transfer:'Gepland',Bron:'Debunkerformulier'},alerts:['Actuele bevoegdheid van het ontvangende asset moet nog worden bevestigd.']},
{id:'supplier',label:'Supplier A',type:'actor',kind:'Fysieke leverancier',x:500,y:85,desc:'Fictieve fysieke leverancier van de oorspronkelijke partij.',facts:{Register:'Geverifieerd',Rol:'Physical supplier'},alerts:[]},
{id:'trader',label:'Trader B',type:'actor',kind:'Contractpartij',x:830,y:100,desc:'Fictieve verkoper zonder fysieke bewaring.',facts:{Rol:'Seller',Eigendom:'Tijdvak onvolledig'},alerts:['Eigendomsoverdracht is niet aan de fysieke transfer gekoppeld.']},
{id:'receiver',label:'Receiver C',type:'actor',kind:'Ontvanger',x:920,y:445,desc:'Fictieve beoogde ontvanger.',facts:{Bevoegdheid:'Niet geverifieerd',Tank:'R-12'},alerts:['Geen actuele bevoegdheidsbron voor product én mogelijke afvalroute.']},
{id:'bdn',label:'BDN-24041',type:'evidence',kind:'Bunker Delivery Note',x:335,y:220,desc:'Oorspronkelijk leveringsdocument.',facts:{Grade:'RMG 380',Massa:'846,0 t',Seal:'S-7781'},alerts:['BDN- en retourmassa verschillen; ROB en verbruik vereisen reconstructie.']},
{id:'sample',label:'Sample S-7781',type:'evidence',kind:'Monster',x:350,y:405,desc:'Fictief verzegeld delivery sample.',facts:{Methode:'Continuous drip',Bewaring:'Aantoonbaar'},alerts:[]},
{id:'invoice',label:'Invoice 9182',type:'evidence',kind:'Factuur',x:750,y:220,desc:'Fictieve factuur voor de oorspronkelijke levering.',facts:{Massa:'846,0 t',Betaling:'Trader B'},alerts:[]},
{id:'return',label:'Return form',type:'evidence',kind:'Debunkerformulier',x:750,y:390,desc:'Formulier voor de voorgenomen terugname.',facts:{Massa:'842,6 t',Status:'Productretour'},alerts:['Productretour is gekozen terwijl gebruiksgeschiktheid nog niet is onderbouwd.']},
{id:'harbour',label:'Harbour authority',type:'oversight',kind:'Havenautoriteit',x:1010,y:175,desc:'Fictieve bevoegde havenfunctie.',facts:{Melding:'Ontvangen',Besluit:'Open'},alerts:[]},
{id:'waste',label:'Waste authority',type:'oversight',kind:'Afvalautoriteit',x:1025,y:565,desc:'Fictieve bevoegde afvalfunctie.',facts:{Dossier:'Niet geopend',Statusvraag:'Open'},alerts:['Nog geen bevoegde beoordeling gekoppeld aan de statusvraag.']}
];
const edges=[['supplier','bdn','levert','ok'],['supplier','batch','herkomst','ok'],['trader','invoice','factureert','ok'],['invoice','bdn','zelfde levering','ok'],['vessel','batch','tank 3P','ok'],['bdn','batch','documenteert','ok'],['sample','bdn','seal S-7781','ok'],['sample','batch','vertegenwoordigt','ok'],['batch','return','retourclaim','open'],['batch','barge','transfer','open'],['return','receiver','bestemming','open'],['barge','receiver','route','open'],['return','harbour','melding','ok'],['return','waste','statusbeoordeling','missing'],['trader','batch','eigendom / risico','open']];
const labels={physical:'Fysieke keten',actor:'Actor',evidence:'Bewijs',oversight:'Toezicht'},ns='http://www.w3.org/2000/svg';let filter='all',only=false,selected=null;const get=id=>nodes.find(n=>n.id===id),show=n=>(filter==='all'||n.type===filter)&&(!only||n.alerts.length),esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function render(){const el=document.getElementById('edgeLayer'),nl=document.getElementById('nodeLayer');el.innerHTML='';nl.innerHTML='';edges.forEach(([ai,bi,label,state])=>{const a=get(ai),b=get(bi);if(!show(a)||!show(b))return;const g=document.createElementNS(ns,'g');g.classList.add('network-edge',state);const l=document.createElementNS(ns,'line');['x1','y1','x2','y2'].forEach((k,i)=>l.setAttribute(k,[a.x,a.y,b.x,b.y][i]));const t=document.createElementNS(ns,'text');t.setAttribute('x',(a.x+b.x)/2);t.setAttribute('y',(a.y+b.y)/2-7);t.textContent=label;g.append(l,t);el.append(g)});nodes.forEach(n=>{if(!show(n))return;const g=document.createElementNS(ns,'g');g.classList.add('network-node',n.type);if(n.alerts.length)g.classList.add('has-alert');if(n.id===selected)g.classList.add('selected');g.setAttribute('transform',`translate(${n.x} ${n.y})`);g.setAttribute('role','button');g.setAttribute('tabindex','0');g.setAttribute('aria-label',`${n.kind} ${n.label}`);const shape=document.createElementNS(ns,n.type==='physical'?'rect':'circle');if(n.type==='physical'){shape.setAttribute('x',-64);shape.setAttribute('y',-27);shape.setAttribute('width',128);shape.setAttribute('height',54);shape.setAttribute('rx',4)}else shape.setAttribute('r',35);const t=document.createElementNS(ns,'text');t.textContent=n.label;t.setAttribute('y',4);g.append(shape,t);if(n.alerts.length){const m=document.createElementNS(ns,'text');m.classList.add('alert-mark');m.textContent='!';m.setAttribute('x',n.type==='physical'?56:27);m.setAttribute('y',n.type==='physical'?-18:-23);g.append(m)}g.onclick=()=>select(n.id);g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(n.id)}};nl.append(g)})}
function select(id){selected=id;const n=get(id);document.getElementById('detailType').textContent=`${labels[n.type]} · ${n.kind}`;document.getElementById('detailTitle').textContent=n.label;document.getElementById('detailDescription').textContent=n.desc;document.getElementById('detailFacts').innerHTML=Object.entries(n.facts).map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('');document.getElementById('detailIndicators').innerHTML=n.alerts.length?`<h3>Open indicatoren</h3>${n.alerts.map(a=>`<p>${esc(a)}</p>`).join('')}`:'<p class="network-clear">Geen open indicator binnen deze demonstratiegegevens.</p>';const rel=edges.filter(e=>e[0]===id||e[1]===id).map(e=>{const o=get(e[0]===id?e[1]:e[0]);return `<li><button data-node="${o.id}">${esc(e[2])} · ${esc(o.label)} <span>${e[3]==='ok'?'bevestigd':e[3]==='missing'?'ontbreekt':'open'}</span></button></li>`}).join('');document.getElementById('detailRelations').innerHTML=`<h3>Relaties</h3><ul>${rel}</ul>`;document.querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>select(b.dataset.node));render()}
document.querySelectorAll('.network-filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('.network-filter').forEach(x=>{const on=x===b;x.classList.toggle('active',on);x.setAttribute('aria-pressed',on)});selected=null;render()});document.getElementById('indicatorOnly').onchange=e=>{only=e.target.checked;selected=null;render()};render();
