(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.DebunkerRisk=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
const coreNames=['bdnNumber','originalBatchId','currentBatchId','reason','technicalImpact','isoStatus','contamination','tankSample','compositeSample','analysisCoversComplaint','receiver','receiverAuthority','destination','declaredStatus','statusRationale'];
const rules=[
{id:'safety',points:24,severity:'red',title:'Veiligheids- of uitvalrisico',text:'Isoleer de partij en laat bevoegde partijen de status beoordelen vóór overdracht.',target:'reason',when:f=>f.technicalImpact==='safety'},
{id:'contamination',points:22,severity:'red',title:'Contaminatie bevestigd',text:'Productroute en afvalroute moeten expliciet worden gescheiden.',target:'quality',when:f=>f.contamination==='confirmed'},
{id:'suspected',points:12,severity:'amber',title:'Contaminatie nog niet uitgesloten',text:'Onderzoek representatief en klachtgericht voordat herlevering wordt overwogen.',target:'quality',when:f=>f.contamination==='suspected'},
{id:'no-samples',points:18,severity:'red',title:'Geen sluitende monsterketen',text:'Tank- en transfermonster ontbreken of zijn niet consistent.',target:'quality',when:f=>f.tankSample==='no'||f.compositeSample==='no'||f.sealConsistency==='no'},
{id:'analysis-gap',points:14,severity:'amber',title:'Analyse dekt de klacht niet',text:'Een bestaand certificaat is geen effectieve controle als relevante parameters ontbreken.',target:'quality',when:f=>f.analysisCoversComplaint==='no'||f.analysisCoversComplaint==='partial'},
{id:'authority',points:24,severity:'red',title:'Geen passende ontvangersbevoegdheid',text:'Verifieer bunker-/product- of afvalrol vóór de slang wordt aangesloten.',target:'transfer',when:f=>f.receiverAuthority==='none'},
{id:'authority-unknown',points:8,severity:'blue',title:'Bevoegdheid niet geverifieerd',text:'Leg register, vergunning en toepasselijke rol vast.',target:'transfer',when:f=>f.receiver&&f.receiverAuthority==='unknown'},
{id:'route',points:15,severity:'red',title:'Bestemming gewijzigd zonder aantoonbare melding',text:'Bevestig feitelijke ontvangst en reden van routewijziging.',target:'transfer',when:f=>f.destinationChanged==='yes-unreported'||f.receiptConfirmed==='no'},
{id:'crossborder',points:7,severity:'amber',title:'Jurisdictiewissel',text:'Koppel toestemming en ontvangstbevestiging over de grens.',target:'transfer',when:f=>f.crossBorder==='yes'&&f.receiptConfirmed!=='yes'},
{id:'mass',points:12,severity:'amber',title:'Onverklaard massaverschil',text:'Verschil is groter dan 1%; controleer methode, correcties en meetonzekerheid.',target:'transfer',when:f=>{let a=+f.plannedMass,b=+f.receivedMass;return a>0&&b>0&&Math.abs(a-b)/a>.01}},
{id:'product-treatment',points:22,severity:'red',title:'Productstatus botst met noodzakelijke behandeling',text:'Voorgenomen behandeling of blending beëindigt afvalstatus niet automatisch.',target:'status',when:f=>f.declaredStatus==='product'&&(f.treatmentNeeded==='substantial'||f.treatmentAuthorised==='no')},
{id:'resupply',points:23,severity:'red',title:'Herlevering vóór aantoonbare behandeling',text:'Stop en laat geschiktheid en status door bevoegde partijen verifiëren.',target:'status',when:f=>f.resupply==='yes-before-treatment'},
{id:'status-empty',points:8,severity:'blue',title:'Statusonderbouwing ontbreekt',text:'Noteer beslisser, feiten, onzekerheid en juridische/technische grond.',target:'status',when:f=>f.declaredStatus&&f.declaredStatus!=='unknown'&&(!f.statusDecider||!f.statusRationale)},
{id:'price',points:7,severity:'amber',title:'Sterke prijsdaling',text:'Onderzoek welke kwaliteits- of behandelingsfactor het verschil verklaart.',target:'reason',when:f=>+f.priceDrop>=40},
{id:'complaints',points:10,severity:'amber',title:'Meerdere afnemers melden problemen',text:'Correlatie op upstream batch en monsters kan verspreiding zichtbaar maken.',target:'reason',when:f=>f.multipleComplaints==='yes'},
{id:'lineage',points:10,severity:'blue',title:'Nieuwe partij-ID zonder afstammingsrecord',text:'Behoud de oorspronkelijke batch als parent-ID.',target:'lineage',when:(f,s)=>f.currentBatchId&&f.originalBatchId&&f.currentBatchId!==f.originalBatchId&&!s.lineage.length}];
function evaluate(fields={},state={lineage:[]}){const active=rules.filter(r=>r.when(fields,state));const raw=active.reduce((n,r)=>n+r.points,0);const score=Math.min(100,Math.round(raw*(active.length>1?.82:1)));const filled=coreNames.filter(k=>fields[k]&&!['unknown',''].includes(fields[k])).length;const coverage=Math.round(filled/coreNames.length*100);let label='Onvoldoende gegevens',note='Vul de kernvelden in om inconsistenties te toetsen.',color='blue';if(active.some(r=>r.severity==='red')){label='Direct beoordelen';note='Eén of meer rode combinaties vragen bevoegde menselijke beoordeling.';color='red'}else if(coverage>=35){if(score>=25){label='Verificatie nodig';note='Inconsistenties of ontbrekende schakels moeten worden onderzocht.';color='amber'}else{label='Geen sterke combinatie';note='Op basis van de ingevulde gegevens; blijf onzekerheden documenteren.';color='green'}}return{active,score,coverage,label,note,color}}
return{rules,coreNames,evaluate}});
